[package]
edition = "2021"
name = "quadtree-over-media"
version = "2.0.0-0.1"
description = """
draw quads over images, using other images
"""
#documentation =
license = "Apache-2.0"
repository = "https://github.com/JacopoWolf/quadtree-over-media-rs/"
keywords = ["quad", "quadtree"]
exclude = [
	"docs/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
rayon = "1.7.0"

clap = { version = "4.3.0", features = ["derive"] }
csscolorparser = "0.6.2"
log = "0.4.17"
simplelog = "0.12.1"

[dev-dependencies]
test-case = "3.1.0"
once_cell = "1.17.1"
