[package]
name = "quadtree-over-media"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
image = "0.24.3"
csscolorparser = "0.6.2"
rayon = "1.5.3"
