[package]
edition = "2021"
name = "quadtree-over-media"
version = "1.0.0-rc.1"
description = """
draw quads over images, using other images
"""
#categories = 
#homepage = 
#documentation =
keywords = ["quad", "quadtree"]
license = "MIT"
repository = "https://github.com/JacopoWolf/quadtree-over-media-rs/"
exclude = [
	"docs/"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
csscolorparser = "0.6.2"
image = "0.24.5"
log = "0.4.17"
rayon = "1.6.1"
simplelog = "0.12.0"

[dev-dependencies]
test-case = "2.2.2"
