[package]
name = "quadtree-over-media"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
clap = { version = "4.1", features = ["derive"] }
csscolorparser = "0.6"
image = "0.24"
rayon = "1.6"
